version: "3.9"

#networks:
#  network_name:
#    external: true

services:
  userloader:
    hostname: icf_userloader
    image: icf_userloader:latest
#    networks:
#    - network_name
#    ports:
#      - [host-port]:[container-port]
#      - [host-port]:[container-port]/udp
    volumes:
      - ${CONFIG:-./config}:/config
    restart: unless-stopped
    
volumes:
  config:
